var add_register_command_factory = new Factory_Registers("AR", Command_Add_Registers);
var subtract_register_command_factory = new Factory_Registers("SR", Command_Subtract_Registers);
var multiply_register_command_factory = new Factory_Registers("MR", Command_Multiply_Registers);
var divide_register_command_factory = new Factory_Registers("DR", Command_Divide_Registers);
var add_memory_command_factory = new Factory_Memory("A", Command_Add_Memory);
var subtract_memory_command_factory = new Factory_Memory("S", Command_Subtract_Memory);
var multiply_memory_command_factory = new Factory_Memory("M", Command_Multiply_Memory);
var divide_memory_command_factory = new Factory_Memory("D", Command_Divide_Memory);
var store_command_factory = new Factory_Memory("ST", Command_Store);
var load_command_factory = new Factory_Memory("L", Command_Load);
var load_address_command_factory = new Factory_Memory("LA", Command_Load_Address);
var load_register_command_factory = new Factory_Registers("DR", Command_Load_Register);
var jump_positive_command_factory = new Factory_Jump("JP", Command_Jump_Positive);
var jump_command_factory = new Factory_Jump("J", Command_Jump);
var jump_zero_command_factory = new Factory_Jump("JZ", Command_Jump_Zero);
var jump_negative_command_factory = new Factory_Jump("JN", Command_Jump_Negative);
var compare_registers_command_factory = new Factory_Registers("CR", Command_Compare_Register);
var compare_memory_command_factory = new Factory_Memory("C", Command_Compare_Memory);
var end = new End_Factory();
compare_memory_command_factory.set_next(end);
compare_registers_command_factory.set_next(compare_memory_command_factory);
jump_negative_command_factory.set_next(compare_registers_command_factory);
jump_zero_command_factory.set_next(jump_negative_command_factory);
jump_command_factory.set_next(jump_zero_command_factory);
jump_positive_command_factory.set_next(jump_command_factory);
load_register_command_factory.set_next(jump_positive_command_factory);
load_address_command_factory.set_next(load_register_command_factory);
load_command_factory.set_next(load_address_command_factory);
store_command_factory.set_next(load_command_factory);
divide_memory_command_factory.set_next(store_command_factory);
multiply_memory_command_factory.set_next(divide_memory_command_factory);
subtract_memory_command_factory.set_next(multiply_memory_command_factory);
add_memory_command_factory.set_next(subtract_memory_command_factory);
divide_register_command_factory.set_next(add_memory_command_factory);
multiply_register_command_factory.set_next(divide_register_command_factory);
subtract_register_command_factory.set_next(multiply_register_command_factory);
add_register_command_factory.set_next(subtract_register_command_factory);

